# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(832, 362)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(7)
        MainWindow.setFont(font)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("font: 10pt \"宋体\";")
        self.tabWidget.setObjectName("tabWidget")
        self.tab0 = QtWidgets.QWidget()
        self.tab0.setObjectName("tab0")
        self.gridLayout = QtWidgets.QGridLayout(self.tab0)
        self.gridLayout.setObjectName("gridLayout")
        self.btnquery = QtWidgets.QPushButton(self.tab0)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnquery.setFont(font)
        self.btnquery.setStyleSheet("font: 9pt \"Agency FB\";")
        self.btnquery.setObjectName("btnquery")
        self.gridLayout.addWidget(self.btnquery, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.startlabel = QtWidgets.QLabel(self.tab0)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.startlabel.setFont(font)
        self.startlabel.setStyleSheet("font: 8pt \"Agency FB\";\n"
"")
        self.startlabel.setObjectName("startlabel")
        self.horizontalLayout_3.addWidget(self.startlabel)
        self.comboBox_satrt = QtWidgets.QComboBox(self.tab0)
        self.comboBox_satrt.setStyleSheet("font: 8pt \"Agency FB\";")
        self.comboBox_satrt.setObjectName("comboBox_satrt")
        self.comboBox_satrt.addItem("")
        self.comboBox_satrt.addItem("")
        self.comboBox_satrt.addItem("")
        self.comboBox_satrt.addItem("")
        self.comboBox_satrt.addItem("")
        self.comboBox_satrt.addItem("")
        self.comboBox_satrt.addItem("")
        self.comboBox_satrt.addItem("")
        self.comboBox_satrt.addItem("")
        self.comboBox_satrt.addItem("")
        self.comboBox_satrt.addItem("")
        self.comboBox_satrt.addItem("")
        self.comboBox_satrt.addItem("")
        self.comboBox_satrt.addItem("")
        self.comboBox_satrt.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_satrt)
        self.endlabel = QtWidgets.QLabel(self.tab0)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.endlabel.setFont(font)
        self.endlabel.setStyleSheet("font: 8pt \"Agency FB\";")
        self.endlabel.setObjectName("endlabel")
        self.horizontalLayout_3.addWidget(self.endlabel)
        self.comboBox_end = QtWidgets.QComboBox(self.tab0)
        self.comboBox_end.setStyleSheet("font: 8pt \"Agency FB\";")
        self.comboBox_end.setObjectName("comboBox_end")
        self.comboBox_end.addItem("")
        self.comboBox_end.addItem("")
        self.comboBox_end.addItem("")
        self.comboBox_end.addItem("")
        self.comboBox_end.addItem("")
        self.comboBox_end.addItem("")
        self.comboBox_end.addItem("")
        self.comboBox_end.addItem("")
        self.comboBox_end.addItem("")
        self.comboBox_end.addItem("")
        self.comboBox_end.addItem("")
        self.comboBox_end.addItem("")
        self.comboBox_end.addItem("")
        self.comboBox_end.addItem("")
        self.comboBox_end.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_end)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.tab0)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        self.gridLayout.addWidget(self.listWidget, 1, 0, 1, 1)
        self.textEdit_query = QtWidgets.QTextEdit(self.tab0)
        self.textEdit_query.setObjectName("textEdit_query")
        self.gridLayout.addWidget(self.textEdit_query, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab0, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.formLayout = QtWidgets.QFormLayout(self.tab2)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnUpload = QtWidgets.QPushButton(self.tab2)
        self.btnUpload.setObjectName("btnUpload")
        self.verticalLayout.addWidget(self.btnUpload)
        self.btnopen = QtWidgets.QPushButton(self.tab2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnopen.setFont(font)
        self.btnopen.setStyleSheet("font: 10pt \"Agency FB\";")
        self.btnopen.setObjectName("btnopen")
        self.verticalLayout.addWidget(self.btnopen)
        self.btnLs = QtWidgets.QPushButton(self.tab2)
        self.btnLs.setStyleSheet("font: 8pt \"宋体\";")
        self.btnLs.setObjectName("btnLs")
        self.verticalLayout.addWidget(self.btnLs)
        self.btnSetup = QtWidgets.QPushButton(self.tab2)
        self.btnSetup.setObjectName("btnSetup")
        self.verticalLayout.addWidget(self.btnSetup)
        self.btnDownload = QtWidgets.QPushButton(self.tab2)
        self.btnDownload.setObjectName("btnDownload")
        self.verticalLayout.addWidget(self.btnDownload)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout)
        self.textEdit_file = QtWidgets.QTextEdit(self.tab2)
        self.textEdit_file.setObjectName("textEdit_file")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textEdit_file)
        self.tabWidget.addTab(self.tab2, "")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab1)
        self.label_2.setStyleSheet("font: 8pt \"Agency FB\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 1, 1, 1)
        self.textBrowser_cmd = QtWidgets.QTextBrowser(self.tab1)
        self.textBrowser_cmd.setObjectName("textBrowser_cmd")
        self.gridLayout_2.addWidget(self.textBrowser_cmd, 1, 0, 5, 1)
        self.label = QtWidgets.QLabel(self.tab1)
        self.label.setStyleSheet("font: 8pt \"Agency FB\";")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 1, 1, 1)
        self.setbtn = QtWidgets.QPushButton(self.tab1)
        self.setbtn.setStyleSheet("font: 10pt \"宋体\";")
        self.setbtn.setObjectName("setbtn")
        self.gridLayout_2.addWidget(self.setbtn, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(17, 168, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 5, 1, 1, 1)
        self.setbtn_1 = QtWidgets.QPushButton(self.tab1)
        self.setbtn_1.setStyleSheet("font: 10pt \"宋体\";")
        self.setbtn_1.setObjectName("setbtn_1")
        self.gridLayout_2.addWidget(self.setbtn_1, 4, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnIP = QtWidgets.QPushButton(self.tab1)
        self.btnIP.setStyleSheet("font: 8pt \"宋体\";")
        self.btnIP.setObjectName("btnIP")
        self.horizontalLayout.addWidget(self.btnIP)
        self.btn_dockerStats = QtWidgets.QPushButton(self.tab1)
        self.btn_dockerStats.setStyleSheet("font: 8pt \"宋体\";")
        self.btn_dockerStats.setObjectName("btn_dockerStats")
        self.horizontalLayout.addWidget(self.btn_dockerStats)
        self.btnReboot = QtWidgets.QPushButton(self.tab1)
        self.btnReboot.setStyleSheet("font: 8pt \"宋体\";")
        self.btnReboot.setObjectName("btnReboot")
        self.horizontalLayout.addWidget(self.btnReboot)
        self.btnPsa = QtWidgets.QPushButton(self.tab1)
        self.btnPsa.setStyleSheet("font: 8pt \"宋体\";")
        self.btnPsa.setObjectName("btnPsa")
        self.horizontalLayout.addWidget(self.btnPsa)
        self.btnPsa1 = QtWidgets.QPushButton(self.tab1)
        self.btnPsa1.setStyleSheet("font: 8pt \"宋体\";")
        self.btnPsa1.setObjectName("btnPsa1")
        self.horizontalLayout.addWidget(self.btnPsa1)
        self.btnTime = QtWidgets.QPushButton(self.tab1)
        self.btnTime.setStyleSheet("font: 8pt \"宋体\";")
        self.btnTime.setObjectName("btnTime")
        self.horizontalLayout.addWidget(self.btnTime)
        self.btnTime1 = QtWidgets.QPushButton(self.tab1)
        self.btnTime1.setStyleSheet("font: 8pt \"宋体\";")
        self.btnTime1.setObjectName("btnTime1")
        self.horizontalLayout.addWidget(self.btnTime1)
        self.IPlabel = QtWidgets.QLabel(self.tab1)
        self.IPlabel.setObjectName("IPlabel")
        self.horizontalLayout.addWidget(self.IPlabel)
        self.IPlineEdit = QtWidgets.QLineEdit(self.tab1)
        self.IPlineEdit.setStyleSheet("font: 8pt \"Agency FB\";")
        self.IPlineEdit.setText("")
        self.IPlineEdit.setObjectName("IPlineEdit")
        self.horizontalLayout.addWidget(self.IPlineEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tab1, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.btnopen.clicked.connect(MainWindow.open)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tool"))
        self.btnquery.setText(_translate("MainWindow", "查询"))
        self.startlabel.setText(_translate("MainWindow", "起始测量点"))
        self.comboBox_satrt.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_satrt.setItemText(1, _translate("MainWindow", "30"))
        self.comboBox_satrt.setItemText(2, _translate("MainWindow", "31"))
        self.comboBox_satrt.setItemText(3, _translate("MainWindow", "32"))
        self.comboBox_satrt.setItemText(4, _translate("MainWindow", "33"))
        self.comboBox_satrt.setItemText(5, _translate("MainWindow", "34"))
        self.comboBox_satrt.setItemText(6, _translate("MainWindow", "35"))
        self.comboBox_satrt.setItemText(7, _translate("MainWindow", "36"))
        self.comboBox_satrt.setItemText(8, _translate("MainWindow", "37"))
        self.comboBox_satrt.setItemText(9, _translate("MainWindow", "38"))
        self.comboBox_satrt.setItemText(10, _translate("MainWindow", "39"))
        self.comboBox_satrt.setItemText(11, _translate("MainWindow", "40"))
        self.comboBox_satrt.setItemText(12, _translate("MainWindow", "41"))
        self.comboBox_satrt.setItemText(13, _translate("MainWindow", "42"))
        self.comboBox_satrt.setItemText(14, _translate("MainWindow", "43"))
        self.endlabel.setText(_translate("MainWindow", "结束测量点"))
        self.comboBox_end.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_end.setItemText(1, _translate("MainWindow", "30"))
        self.comboBox_end.setItemText(2, _translate("MainWindow", "31"))
        self.comboBox_end.setItemText(3, _translate("MainWindow", "32"))
        self.comboBox_end.setItemText(4, _translate("MainWindow", "33"))
        self.comboBox_end.setItemText(5, _translate("MainWindow", "34"))
        self.comboBox_end.setItemText(6, _translate("MainWindow", "35"))
        self.comboBox_end.setItemText(7, _translate("MainWindow", "36"))
        self.comboBox_end.setItemText(8, _translate("MainWindow", "37"))
        self.comboBox_end.setItemText(9, _translate("MainWindow", "38"))
        self.comboBox_end.setItemText(10, _translate("MainWindow", "39"))
        self.comboBox_end.setItemText(11, _translate("MainWindow", "40"))
        self.comboBox_end.setItemText(12, _translate("MainWindow", "41"))
        self.comboBox_end.setItemText(13, _translate("MainWindow", "42"))
        self.comboBox_end.setItemText(14, _translate("MainWindow", "43"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "8900测量点状态"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "8901测量点性质"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "8902测量点地址"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "8906本地网络访问地址"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "8907父节点地址"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "8911测量点CT变比"))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "B611A相电压"))
        item = self.listWidget.item(7)
        item.setText(_translate("MainWindow", "B612B相电压"))
        item = self.listWidget.item(8)
        item.setText(_translate("MainWindow", "B613C相电压"))
        item = self.listWidget.item(9)
        item.setText(_translate("MainWindow", "B621A相电流"))
        item = self.listWidget.item(10)
        item.setText(_translate("MainWindow", "B622B相电流"))
        item = self.listWidget.item(11)
        item.setText(_translate("MainWindow", "B623C相电流"))
        item = self.listWidget.item(12)
        item.setText(_translate("MainWindow", "8E21A相电流(一次侧)"))
        item = self.listWidget.item(13)
        item.setText(_translate("MainWindow", "8E22B相电流(一次侧)"))
        item = self.listWidget.item(14)
        item.setText(_translate("MainWindow", "8E23C相电流(一次侧)"))
        item = self.listWidget.item(15)
        item.setText(_translate("MainWindow", "D520变压器油温"))
        item = self.listWidget.item(16)
        item.setText(_translate("MainWindow", "D521环境温度"))
        item = self.listWidget.item(17)
        item.setText(_translate("MainWindow", "D525环境湿度"))
        item = self.listWidget.item(18)
        item.setText(_translate("MainWindow", "D528变压器箱内温度"))
        item = self.listWidget.item(19)
        item.setText(_translate("MainWindow", "890B SIM卡手机号"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab0), _translate("MainWindow", "数据查询"))
        self.btnUpload.setText(_translate("MainWindow", "导入U盘文件"))
        self.btnopen.setText(_translate("MainWindow", "打开文件"))
        self.btnLs.setText(_translate("MainWindow", "ls -l"))
        self.btnSetup.setText(_translate("MainWindow", "一键部署"))
        self.btnDownload.setText(_translate("MainWindow", "下载日志"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "程序部署"))
        self.label_2.setText(_translate("MainWindow", "测量点参数"))
        self.label.setText(_translate("MainWindow", "终端参数"))
        self.setbtn.setText(_translate("MainWindow", "上行通讯参数"))
        self.setbtn_1.setText(_translate("MainWindow", "测量点通讯参数"))
        self.btnIP.setText(_translate("MainWindow", "ifconfig"))
        self.btn_dockerStats.setText(_translate("MainWindow", "docker ps"))
        self.btnReboot.setText(_translate("MainWindow", "Reboot"))
        self.btnPsa.setText(_translate("MainWindow", "psa"))
        self.btnPsa1.setText(_translate("MainWindow", "display_psa"))
        self.btnTime.setText(_translate("MainWindow", "终端对时1"))
        self.btnTime1.setText(_translate("MainWindow", "终端对时2"))
        self.IPlabel.setText(_translate("MainWindow", "IP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "维护管理"))
        self.actionopen.setText(_translate("MainWindow", "Open"))

