# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tool_ui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(752, 530)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("rgb(127, 134, 129)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("font: 12pt \"宋体\";")
        self.tabWidget.setObjectName("tabWidget")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.textEdit_send = QtWidgets.QTextEdit(self.tab2)
        self.textEdit_send.setGeometry(QtCore.QRect(20, 100, 371, 251))
        self.textEdit_send.setObjectName("textEdit_send")
        self.textBrowser_recv = QtWidgets.QTextBrowser(self.tab2)
        self.textBrowser_recv.setGeometry(QtCore.QRect(430, 130, 256, 192))
        self.textBrowser_recv.setObjectName("textBrowser_recv")
        self.btnsend = QtWidgets.QPushButton(self.tab2)
        self.btnsend.setGeometry(QtCore.QRect(180, 360, 75, 25))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnsend.setFont(font)
        self.btnsend.setStyleSheet("font: 10pt \"Agency FB\";")
        self.btnsend.setObjectName("btnsend")
        self.layoutWidget = QtWidgets.QWidget(self.tab2)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 30, 320, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnopen = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnopen.setFont(font)
        self.btnopen.setStyleSheet("font: 10pt \"Agency FB\";")
        self.btnopen.setObjectName("btnopen")
        self.horizontalLayout.addWidget(self.btnopen)
        self.btnsetup = QtWidgets.QPushButton(self.layoutWidget)
        self.btnsetup.setObjectName("btnsetup")
        self.horizontalLayout.addWidget(self.btnsetup)
        self.btnupload = QtWidgets.QPushButton(self.layoutWidget)
        self.btnupload.setObjectName("btnupload")
        self.horizontalLayout.addWidget(self.btnupload)
        self.btndownload = QtWidgets.QPushButton(self.layoutWidget)
        self.btndownload.setObjectName("btndownload")
        self.horizontalLayout.addWidget(self.btndownload)
        self.tabWidget.addTab(self.tab2, "")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.IPlabel = QtWidgets.QLabel(self.tab1)
        self.IPlabel.setObjectName("IPlabel")
        self.horizontalLayout_2.addWidget(self.IPlabel)
        self.IPlineEdit = QtWidgets.QLineEdit(self.tab1)
        self.IPlineEdit.setObjectName("IPlineEdit")
        self.horizontalLayout_2.addWidget(self.IPlineEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dockerstatsbtn = QtWidgets.QPushButton(self.tab1)
        self.dockerstatsbtn.setStyleSheet("font: 10pt \"宋体\";")
        self.dockerstatsbtn.setObjectName("dockerstatsbtn")
        self.horizontalLayout_3.addWidget(self.dockerstatsbtn)
        self.adjusttimebtn = QtWidgets.QPushButton(self.tab1)
        self.adjusttimebtn.setStyleSheet("font: 10pt \"宋体\";")
        self.adjusttimebtn.setObjectName("adjusttimebtn")
        self.horizontalLayout_3.addWidget(self.adjusttimebtn)
        self.rebootbtn = QtWidgets.QPushButton(self.tab1)
        self.rebootbtn.setStyleSheet("font: 10pt \"宋体\";")
        self.rebootbtn.setObjectName("rebootbtn")
        self.horizontalLayout_3.addWidget(self.rebootbtn)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.textBrowser_docker = QtWidgets.QTextBrowser(self.tab1)
        self.textBrowser_docker.setObjectName("textBrowser_docker")
        self.gridLayout_4.addWidget(self.textBrowser_docker, 1, 0, 1, 2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.tab1)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.setbtn_2 = QtWidgets.QPushButton(self.tab1)
        self.setbtn_2.setStyleSheet("font: 10pt \"宋体\";")
        self.setbtn_2.setObjectName("setbtn_2")
        self.verticalLayout_4.addWidget(self.setbtn_2)
        self.label_2 = QtWidgets.QLabel(self.tab1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.setbtn_1 = QtWidgets.QPushButton(self.tab1)
        self.setbtn_1.setStyleSheet("font: 10pt \"宋体\";")
        self.setbtn_1.setObjectName("setbtn_1")
        self.verticalLayout_4.addWidget(self.setbtn_1)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab1, "")
        self.tab0 = QtWidgets.QWidget()
        self.tab0.setObjectName("tab0")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.startlabel = QtWidgets.QLabel(self.tab0)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.startlabel.setFont(font)
        self.startlabel.setStyleSheet("font: 7pt \"Agency FB\";\n"
"font: 9pt \"Agency FB\";")
        self.startlabel.setObjectName("startlabel")
        self.verticalLayout_3.addWidget(self.startlabel)
        self.comboBox_2 = QtWidgets.QComboBox(self.tab0)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox_2)
        self.endlabel = QtWidgets.QLabel(self.tab0)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.endlabel.setFont(font)
        self.endlabel.setStyleSheet("font: 7pt \"Agency FB\";\n"
"font: 9pt \"Agency FB\";")
        self.endlabel.setObjectName("endlabel")
        self.verticalLayout_3.addWidget(self.endlabel)
        self.comboBox = QtWidgets.QComboBox(self.tab0)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.para = QtWidgets.QLabel(self.tab0)
        self.para.setStyleSheet("font: 9pt \"Agency FB\";")
        self.para.setObjectName("para")
        self.verticalLayout.addWidget(self.para)
        self.checkBox_stats = QtWidgets.QCheckBox(self.tab0)
        self.checkBox_stats.setStyleSheet("font: 9pt \"Agency FB\";")
        self.checkBox_stats.setObjectName("checkBox_stats")
        self.verticalLayout.addWidget(self.checkBox_stats)
        self.checkBox_nature = QtWidgets.QCheckBox(self.tab0)
        self.checkBox_nature.setStyleSheet("font: 9pt \"Agency FB\";")
        self.checkBox_nature.setObjectName("checkBox_nature")
        self.verticalLayout.addWidget(self.checkBox_nature)
        self.checkBox_adr = QtWidgets.QCheckBox(self.tab0)
        self.checkBox_adr.setStyleSheet("font: 9pt \"Agency FB\";")
        self.checkBox_adr.setObjectName("checkBox_adr")
        self.verticalLayout.addWidget(self.checkBox_adr)
        self.checkBox_MAC = QtWidgets.QCheckBox(self.tab0)
        self.checkBox_MAC.setStyleSheet("font: 9pt \"Agency FB\";")
        self.checkBox_MAC.setObjectName("checkBox_MAC")
        self.verticalLayout.addWidget(self.checkBox_MAC)
        self.checkBox_father = QtWidgets.QCheckBox(self.tab0)
        self.checkBox_father.setStyleSheet("font: 9pt \"Agency FB\";")
        self.checkBox_father.setObjectName("checkBox_father")
        self.verticalLayout.addWidget(self.checkBox_father)
        self.checkBox_IP = QtWidgets.QCheckBox(self.tab0)
        self.checkBox_IP.setStyleSheet("font: 9pt \"Agency FB\";")
        self.checkBox_IP.setObjectName("checkBox_IP")
        self.verticalLayout.addWidget(self.checkBox_IP)
        self.checkBox_CT = QtWidgets.QCheckBox(self.tab0)
        self.checkBox_CT.setStyleSheet("font: 9pt \"Agency FB\";")
        self.checkBox_CT.setObjectName("checkBox_CT")
        self.verticalLayout.addWidget(self.checkBox_CT)
        self.checkBox_num = QtWidgets.QCheckBox(self.tab0)
        self.checkBox_num.setStyleSheet("font: 9pt \"Agency FB\";")
        self.checkBox_num.setObjectName("checkBox_num")
        self.verticalLayout.addWidget(self.checkBox_num)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 1, 1, 2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.data = QtWidgets.QLabel(self.tab0)
        self.data.setStyleSheet("font: 9pt \"Agency FB\";")
        self.data.setObjectName("data")
        self.verticalLayout_2.addWidget(self.data)
        self.checkBox_B611 = QtWidgets.QCheckBox(self.tab0)
        self.checkBox_B611.setStyleSheet("font: 9pt \"Agency FB\";")
        self.checkBox_B611.setObjectName("checkBox_B611")
        self.verticalLayout_2.addWidget(self.checkBox_B611)
        self.checkBox_B612 = QtWidgets.QCheckBox(self.tab0)
        self.checkBox_B612.setStyleSheet("font: 9pt \"Agency FB\";")
        self.checkBox_B612.setObjectName("checkBox_B612")
        self.verticalLayout_2.addWidget(self.checkBox_B612)
        self.checkBox_B613 = QtWidgets.QCheckBox(self.tab0)
        self.checkBox_B613.setStyleSheet("font: 9pt \"Agency FB\";")
        self.checkBox_B613.setObjectName("checkBox_B613")
        self.verticalLayout_2.addWidget(self.checkBox_B613)
        self.checkBox_B621 = QtWidgets.QCheckBox(self.tab0)
        self.checkBox_B621.setStyleSheet("font: 9pt \"Agency FB\";")
        self.checkBox_B621.setObjectName("checkBox_B621")
        self.verticalLayout_2.addWidget(self.checkBox_B621)
        self.checkBox_B622 = QtWidgets.QCheckBox(self.tab0)
        self.checkBox_B622.setStyleSheet("font: 9pt \"Agency FB\";")
        self.checkBox_B622.setObjectName("checkBox_B622")
        self.verticalLayout_2.addWidget(self.checkBox_B622)
        self.checkBox_B623 = QtWidgets.QCheckBox(self.tab0)
        self.checkBox_B623.setStyleSheet("font: 9pt \"Agency FB\";")
        self.checkBox_B623.setObjectName("checkBox_B623")
        self.verticalLayout_2.addWidget(self.checkBox_B623)
        self.checkBox_8E21 = QtWidgets.QCheckBox(self.tab0)
        self.checkBox_8E21.setStyleSheet("font: 9pt \"Agency FB\";")
        self.checkBox_8E21.setObjectName("checkBox_8E21")
        self.verticalLayout_2.addWidget(self.checkBox_8E21)
        self.checkBox_8E22 = QtWidgets.QCheckBox(self.tab0)
        self.checkBox_8E22.setStyleSheet("font: 9pt \"Agency FB\";")
        self.checkBox_8E22.setObjectName("checkBox_8E22")
        self.verticalLayout_2.addWidget(self.checkBox_8E22)
        self.checkBox_8E23 = QtWidgets.QCheckBox(self.tab0)
        self.checkBox_8E23.setStyleSheet("font: 9pt \"Agency FB\";")
        self.checkBox_8E23.setObjectName("checkBox_8E23")
        self.verticalLayout_2.addWidget(self.checkBox_8E23)
        self.checkBox_D520 = QtWidgets.QCheckBox(self.tab0)
        self.checkBox_D520.setStyleSheet("font: 9pt \"Agency FB\";")
        self.checkBox_D520.setObjectName("checkBox_D520")
        self.verticalLayout_2.addWidget(self.checkBox_D520)
        self.checkBox_D521 = QtWidgets.QCheckBox(self.tab0)
        self.checkBox_D521.setStyleSheet("font: 9pt \"Agency FB\";")
        self.checkBox_D521.setObjectName("checkBox_D521")
        self.verticalLayout_2.addWidget(self.checkBox_D521)
        self.checkBox_D525 = QtWidgets.QCheckBox(self.tab0)
        self.checkBox_D525.setStyleSheet("font: 9pt \"Agency FB\";")
        self.checkBox_D525.setObjectName("checkBox_D525")
        self.verticalLayout_2.addWidget(self.checkBox_D525)
        self.checkBox_D528 = QtWidgets.QCheckBox(self.tab0)
        self.checkBox_D528.setStyleSheet("font: 9pt \"Agency FB\";")
        self.checkBox_D528.setObjectName("checkBox_D528")
        self.verticalLayout_2.addWidget(self.checkBox_D528)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 3, 2, 2)
        self.textBrowser_query = QtWidgets.QTextBrowser(self.tab0)
        self.textBrowser_query.setObjectName("textBrowser_query")
        self.gridLayout_3.addWidget(self.textBrowser_query, 1, 0, 2, 1)
        self.query_btn = QtWidgets.QPushButton(self.tab0)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.query_btn.setFont(font)
        self.query_btn.setStyleSheet("font: 10pt \"Agency FB\";")
        self.query_btn.setObjectName("query_btn")
        self.gridLayout_3.addWidget(self.query_btn, 2, 1, 1, 1)
        self.Abtn = QtWidgets.QPushButton(self.tab0)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Abtn.setFont(font)
        self.Abtn.setStyleSheet("font: 10pt \"Agency FB\";")
        self.Abtn.setObjectName("Abtn")
        self.gridLayout_3.addWidget(self.Abtn, 2, 2, 1, 1)
        self.humbtn = QtWidgets.QPushButton(self.tab0)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.humbtn.setFont(font)
        self.humbtn.setStyleSheet("font: 10pt \"Agency FB\";")
        self.humbtn.setObjectName("humbtn")
        self.gridLayout_3.addWidget(self.humbtn, 2, 3, 1, 1)
        self.tempbtn = QtWidgets.QPushButton(self.tab0)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tempbtn.setFont(font)
        self.tempbtn.setStyleSheet("font: 10pt \"Agency FB\";")
        self.tempbtn.setObjectName("tempbtn")
        self.gridLayout_3.addWidget(self.tempbtn, 2, 4, 1, 1)
        self.ipbtn = QtWidgets.QPushButton(self.tab0)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ipbtn.setFont(font)
        self.ipbtn.setStyleSheet("font: 10pt \"Agency FB\";")
        self.ipbtn.setObjectName("ipbtn")
        self.gridLayout_3.addWidget(self.ipbtn, 2, 5, 1, 1)
        self.query_btn.raise_()
        self.Abtn.raise_()
        self.humbtn.raise_()
        self.tempbtn.raise_()
        self.ipbtn.raise_()
        self.textBrowser_query.raise_()
        self.tabWidget.addTab(self.tab0, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 752, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.menu.addAction(self.actionopen)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tool"))
        self.textEdit_send.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'宋体\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btnsend.setText(_translate("MainWindow", "发送"))
        self.btnopen.setText(_translate("MainWindow", "打开"))
        self.btnsetup.setText(_translate("MainWindow", "一键部署"))
        self.btnupload.setText(_translate("MainWindow", "上传"))
        self.btndownload.setText(_translate("MainWindow", "下载"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "程序部署"))
        self.IPlabel.setText(_translate("MainWindow", "目标IP"))
        self.IPlineEdit.setText(_translate("MainWindow", "172.30.32.129"))
        self.dockerstatsbtn.setText(_translate("MainWindow", "容器状态"))
        self.adjusttimebtn.setText(_translate("MainWindow", "终端对时"))
        self.rebootbtn.setText(_translate("MainWindow", "容器复位"))
        self.label.setText(_translate("MainWindow", "终端参数"))
        self.setbtn_2.setText(_translate("MainWindow", "上行通讯参数"))
        self.label_2.setText(_translate("MainWindow", "测量点参数"))
        self.setbtn_1.setText(_translate("MainWindow", "测量点通讯参数"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "维护管理"))
        self.startlabel.setText(_translate("MainWindow", "起始测量点"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "30"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "31"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "32"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "33"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "34"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "35"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "36"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "37"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "38"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "39"))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "40"))
        self.comboBox_2.setItemText(12, _translate("MainWindow", "41"))
        self.comboBox_2.setItemText(13, _translate("MainWindow", "42"))
        self.comboBox_2.setItemText(14, _translate("MainWindow", "43"))
        self.endlabel.setText(_translate("MainWindow", "结束测量点"))
        self.comboBox.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox.setItemText(1, _translate("MainWindow", "30"))
        self.comboBox.setItemText(2, _translate("MainWindow", "31"))
        self.comboBox.setItemText(3, _translate("MainWindow", "32"))
        self.comboBox.setItemText(4, _translate("MainWindow", "33"))
        self.comboBox.setItemText(5, _translate("MainWindow", "34"))
        self.comboBox.setItemText(6, _translate("MainWindow", "35"))
        self.comboBox.setItemText(7, _translate("MainWindow", "36"))
        self.comboBox.setItemText(8, _translate("MainWindow", "37"))
        self.comboBox.setItemText(9, _translate("MainWindow", "38"))
        self.comboBox.setItemText(10, _translate("MainWindow", "39"))
        self.comboBox.setItemText(11, _translate("MainWindow", "40"))
        self.comboBox.setItemText(12, _translate("MainWindow", "41"))
        self.comboBox.setItemText(13, _translate("MainWindow", "42"))
        self.comboBox.setItemText(14, _translate("MainWindow", "43"))
        self.para.setText(_translate("MainWindow", "测量点参数选择"))
        self.checkBox_stats.setText(_translate("MainWindow", "8900 测量点状态"))
        self.checkBox_nature.setText(_translate("MainWindow", "8901 测量点性质"))
        self.checkBox_adr.setText(_translate("MainWindow", "8902 测量点地址"))
        self.checkBox_MAC.setText(_translate("MainWindow", "8906 本地网络访问地址"))
        self.checkBox_father.setText(_translate("MainWindow", "8907 父节点地址"))
        self.checkBox_IP.setText(_translate("MainWindow", "890A SIM卡IP地址"))
        self.checkBox_CT.setText(_translate("MainWindow", "8911 测量点CT变比"))
        self.checkBox_num.setText(_translate("MainWindow", "890B SIM卡手机号"))
        self.data.setText(_translate("MainWindow", "测量点数据选择"))
        self.checkBox_B611.setText(_translate("MainWindow", "B611 A相电压"))
        self.checkBox_B612.setText(_translate("MainWindow", "B612 B相电压"))
        self.checkBox_B613.setText(_translate("MainWindow", "B613 C相电压"))
        self.checkBox_B621.setText(_translate("MainWindow", "B621 A相电流"))
        self.checkBox_B622.setText(_translate("MainWindow", "B622 B相电流"))
        self.checkBox_B623.setText(_translate("MainWindow", "B623 C相电流"))
        self.checkBox_8E21.setText(_translate("MainWindow", "8E21 A相电流(一次侧)"))
        self.checkBox_8E22.setText(_translate("MainWindow", "8E22 B相电流(一次侧)"))
        self.checkBox_8E23.setText(_translate("MainWindow", "8E23 C相电流(一次侧)"))
        self.checkBox_D520.setText(_translate("MainWindow", "D520 变压器油温"))
        self.checkBox_D521.setText(_translate("MainWindow", "D521 环境温度"))
        self.checkBox_D525.setText(_translate("MainWindow", "D525 环境湿度"))
        self.checkBox_D528.setText(_translate("MainWindow", "D528 变压器箱内温度"))
        self.textBrowser_query.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'宋体\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.query_btn.setText(_translate("MainWindow", "查询"))
        self.Abtn.setText(_translate("MainWindow", "A相电压"))
        self.humbtn.setText(_translate("MainWindow", "环境湿度"))
        self.tempbtn.setText(_translate("MainWindow", "环境温度"))
        self.ipbtn.setText(_translate("MainWindow", "测量点IP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab0), _translate("MainWindow", "数据查询"))
        self.menu.setTitle(_translate("MainWindow", "File"))
        self.actionopen.setText(_translate("MainWindow", "Open"))


