# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PreviewApp.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(752, 561)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("rgb(127, 134, 129)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("font: 12pt \"宋体\";")
        self.tabWidget.setObjectName("tabWidget")
        self.tab0 = QtWidgets.QWidget()
        self.tab0.setObjectName("tab0")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableView = QtWidgets.QTableView(self.tab0)
        self.tableView.setObjectName("tableView")
        self.gridLayout_3.addWidget(self.tableView, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab0, "")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.IPlabel = QtWidgets.QLabel(self.tab1)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.IPlabel.setFont(font)
        self.IPlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.IPlabel.setObjectName("IPlabel")
        self.horizontalLayout.addWidget(self.IPlabel)
        self.comboBox1 = QtWidgets.QComboBox(self.tab1)
        self.comboBox1.setObjectName("comboBox1")
        self.horizontalLayout.addWidget(self.comboBox1)
        self.ZDlabel = QtWidgets.QLabel(self.tab1)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ZDlabel.setFont(font)
        self.ZDlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ZDlabel.setObjectName("ZDlabel")
        self.horizontalLayout.addWidget(self.ZDlabel)
        self.comboBox2 = QtWidgets.QComboBox(self.tab1)
        self.comboBox2.setObjectName("comboBox2")
        self.horizontalLayout.addWidget(self.comboBox2)
        self.gridLayout_5.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tableView1 = QtWidgets.QTableView(self.tab1)
        self.tableView1.setObjectName("tableView1")
        self.gridLayout_5.addWidget(self.tableView1, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn6 = QtWidgets.QPushButton(self.tab1)
        self.btn6.setObjectName("btn6")
        self.horizontalLayout_2.addWidget(self.btn6)
        self.btn7 = QtWidgets.QPushButton(self.tab1)
        self.btn7.setObjectName("btn7")
        self.horizontalLayout_2.addWidget(self.btn7)
        self.btn1 = QtWidgets.QPushButton(self.tab1)
        self.btn1.setObjectName("btn1")
        self.horizontalLayout_2.addWidget(self.btn1)
        self.btn2 = QtWidgets.QPushButton(self.tab1)
        self.btn2.setObjectName("btn2")
        self.horizontalLayout_2.addWidget(self.btn2)
        self.label1 = QtWidgets.QLabel(self.tab1)
        self.label1.setObjectName("label1")
        self.horizontalLayout_2.addWidget(self.label1)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.tab1)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_5.addWidget(self.textEdit, 3, 0, 1, 1)
        self.tableView1.raise_()
        self.textEdit.raise_()
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label2 = QtWidgets.QLabel(self.tab2)
        self.label2.setText("")
        self.label2.setObjectName("label2")
        self.gridLayout_4.addWidget(self.label2, 0, 0, 1, 3)
        self.btn3 = QtWidgets.QPushButton(self.tab2)
        self.btn3.setObjectName("btn3")
        self.gridLayout_4.addWidget(self.btn3, 1, 0, 1, 1)
        self.btn4 = QtWidgets.QPushButton(self.tab2)
        self.btn4.setObjectName("btn4")
        self.gridLayout_4.addWidget(self.btn4, 1, 1, 1, 1)
        self.btn5 = QtWidgets.QPushButton(self.tab2)
        self.btn5.setObjectName("btn5")
        self.gridLayout_4.addWidget(self.btn5, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tool"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab0), _translate("MainWindow", "终端概览"))
        self.IPlabel.setText(_translate("MainWindow", "IP地址"))
        self.ZDlabel.setText(_translate("MainWindow", "终端地址"))
        self.btn6.setText(_translate("MainWindow", "获取容器"))
        self.btn7.setText(_translate("MainWindow", "刷新页面"))
        self.btn1.setText(_translate("MainWindow", "增加容器"))
        self.btn2.setText(_translate("MainWindow", "删除容器"))
        self.label1.setText(_translate("MainWindow", "连接成功/失败"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'宋体\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">welcome connection ...</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "终端APP"))
        self.btn3.setText(_translate("MainWindow", "cpu占有率"))
        self.btn4.setText(_translate("MainWindow", "内存占有率"))
        self.btn5.setText(_translate("MainWindow", "cpu温度"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Graphs"))


